emoji script

diff --git a/scripts/path/emoji b/scripts/path/emoji
--- a/scripts/path/emoji
+++ b/scripts/path/emoji
@@ -3,16 +3,20 @@
 # process flags
 COPY=0
 if [ "$#" -gt 0 ]; then
-    while getopts 'c' flag; do
+    while getopts 'ci' flag; do
         case "${flag}" in
             c) COPY=1;;
             *) echo "Unexpected option ${flag}"
             exit 1 ;;
         esac
     done
-fi
 
-shift $((OPTIND-1))
+    # drop processed arguments
+    shift $((OPTIND-1))
+    INPUT=$@
+else
+    read -r INPUT
+fi
 
 # save emoji json in /tmp if not already there
 if [ ! -f "/tmp/emoji.json" ]; then
@@ -21,21 +25,23 @@ if [ ! -f "/tmp/emoji.json" ]; then
     # TODO: invalid token
 fi
 
-# slug prefix expression
-EXP="e[0-9]-[0-9]+-"
-
 # get emojis and slugs
-EMOJIS=$(cat "/tmp/emoji.json" | jq -r '.[] | "\(.character) \(.slug)"')
+EMOJIS=$(cat "/tmp/emoji.json" | jq -r '.[] | "\(.character) \(.slug | sub("e[0-9]+-[0-9]+-"; ""))"')
 
 # look for match on user input
-MATCH=$(echo "$EMOJIS" | awk '{print $2}' | rg -x "$EXP$(echo $@ | tr ' ' '-')")
+MATCH=$(echo "$EMOJIS" | awk '{print $2}' | rg -x "$(echo $INPUT | tr ' ' '-')")
 
 if [ -n "$MATCH" ]; then
     # if there's a match, return it
     CHOICE=$(echo "$EMOJIS" | rg $MATCH)
 else
-    # otherwise push to fzf with the user's input as a starting query
-    CHOICE=$(echo "$EMOJIS" | sed -E "s/$EXP//g" | fzf --height=~10 --select-1 --exit-0 --query="$@")
+    # avoid using fzf when calling from inside vim
+    if [ -n "$VIMRUNTIME" ]; then
+        echo "$INPUT not found"
+        exit 1
+    else
+        CHOICE=$(echo "$EMOJIS" | fzf --height=~10 --select-1 --exit-0 --query="$INPUT")
+    fi
 fi
 
 # flagged behavior
