build script rebuild

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -48,43 +48,43 @@ function gh_commit {
 }
 
 function rebuild {
-  local ask_commit dry_run force_commit hash host switch
+    local ask_commit dry_run force_commit hash host switch
 
-  dry_run=$1
-  ask_commit=$2
-  force_commit=$3
-  host=$(cat "$NIX_HOST_PATH")
-  switch="switch"
+    dry_run=$1
+    ask_commit=$2
+    force_commit=$3
+    host=$(cat "$NIX_HOST_PATH")
+    switch="switch"
 
-  if $dry_run; then
-      switch="dry-activate"
-  fi
+    if $dry_run; then
+        switch="dry-activate"
+    fi
 
-  sudo -v
-  (sudo nixos-rebuild "$switch" \
-      --impure --flake \
-      "$NIX_CONFIG_PATH"#"$host" 2>&1 \
-      | sudo tee nixos-switch.log > /dev/null) &
-  spinner $! "Rebuilding"
+    sudo -v
+    (sudo nixos-rebuild "$switch" \
+        --impure --flake \
+        "$NIX_CONFIG_PATH"#"$host" 2>&1 \
+        | sudo tee nixos-switch.log > /dev/null) &
+    spinner $! "Rebuilding (see $NIX_CONFIG_PATH/nixos-switch.log)"
 
-  if test "${PIPESTATUS[0]}" -eq 0; then
+    if test "${PIPESTATUS[0]}" -eq 0; then
 
-      echo ":blue-circle: Build Succeeded" | emoji -m
-      if [[ $dry_run == true ]]; then  # do not commit on dry runs
-          echo "(dry run; no changes committed)"
-      else
-          if [[ $force_commit == true ]]; then echo hello; gh_commit
-          elif [[ $ask_commit == true ]]; then
-              read -rp "Do you want to commit this configuration? (y/n) " yn
-              case $yn in
-                  [yY] ) gh_commit;;
-                  [nN] ) exit 0;;
-                  * ) echo 'invalid response'; exit 1;;
-              esac
-          fi
-      fi
+        echo ":blue-circle: Build Succeeded" | emoji -m
+        if [[ $dry_run == true ]]; then  # do not commit on dry runs
+            echo "(dry run; no changes committed)"
+        else
+            if [[ $force_commit == true ]]; then echo hello; gh_commit
+            elif [[ $ask_commit == true ]]; then
+                read -rp "Do you want to commit this configuration? (y/n) " yn
+                case $yn in
+                    [yY] ) gh_commit;;
+                    [nN] ) exit 0;;
+                    * ) echo 'invalid response'; exit 1;;
+                esac
+            fi
+        fi
 
-  else
+    else
 
       echo ":red-circle: Build Failed..." | emoji -m
       hash=$(rg --color=always 'hash mismatch' < nixos-switch.log)
@@ -96,7 +96,7 @@ function rebuild {
           rg --color=always error < nixos-switch.log
       fi
 
-  fi
+    fi
 }
 
 function main {
