552 current  2024-09-01 09:11:59  24.05.20240827.36bae45  6.6.47                          *

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -28,14 +28,18 @@ function choose_host {
     fi
 }
 
-set -e
 cd ~/.dotfiles/nixos
 echo "Rebuilding ❄️NixOS..."
 
 choose_host
 
 git diff -U0 **/*.nix
-sudo nixos-rebuild switch --flake --impure .#$(cat $NIX_HOST_PATH) &>nixos-switch.log \
-    || cat nixos-switch.log | rg --color=always error && false
+sudo nixos-rebuild switch --impure --flake .#$(cat $NIX_HOST_PATH) &>nixos-switch.log
 
-git commit -am "$(nixos-rebuild list-generations | rg current)"
+if [[ $? -gt 0 ]]; then
+    echo "Build failed..."
+    cat nixos-switch.log | rg --color=always error
+else
+    git commit -am "$(nixos-rebuild list-generations | rg current)"
+fi
+
