fixing build script

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -40,30 +40,34 @@ function choose_host {
 }
 
 function rebuild {
-    host=$(cat "$NIX_HOST_PATH")
+  host=$(cat "$NIX_HOST_PATH")
 
-    [[ $1 == true ]] && dry="--dry-run "
-    sudo nixos-rebuild switch --impure --flake "$dry".#"$host" | tee nixos-switch.log
+  if [[ $1 == true ]]; then
+    switch="dry-activate"
+  else
+    switch="switch"
+  fi
+  sudo nixos-rebuild "$switch" --impure --flake .#"$host" 2>&1 | sudo tee nixos-switch.log > /dev/null
 
-    #  [[ $? -eq 0 ]] throws an LSP error
-    if test $? -eq 0; then
-        echo "🔵 Build Succeeded"
-        if [[ $1 == true ]]; then  # do not commit on dry runs
-            git commit -am "$(nixos-rebuild list-generations | rg current)"
-        else
-            echo "(dry run; no changes applied)"
-        fi
-    else
-        echo "🔴 Build Failed..."
-        hash=$(rg --color=always 'hash mismatch' < nixos-switch.log)
-        if [[ -n $hash ]]; then
-            echo "$hash"
-            rg --color=always 'specified:' < nixos-switch.log
-            rg --color=always 'got:' < nixos-switch.log
-        else
-            rg --color=always error < nixos-switch.log
-        fi
-    fi
+  #  [[ $? -eq 0 ]] throws an LSP error
+  if test $? -eq 0; then
+      echo "🔵 Build Succeeded"
+      if [[ $1 == true ]]; then  # do not commit on dry runs
+          echo "(dry run; no changes applied)"
+      else
+          git commit -am "$(nixos-rebuild list-generations | rg current)"
+      fi
+  else
+      echo "🔴 Build Failed..."
+      hash=$(rg --color=always 'hash mismatch' < nixos-switch.log)
+      if [[ -n $hash ]]; then
+          echo "$hash"
+          rg --color=always 'specified:' < nixos-switch.log
+          rg --color=always 'got:' < nixos-switch.log
+      else
+          rg --color=always error < nixos-switch.log
+      fi
+  fi
 }
 
 cd "$HOME/.dotfiles/nixos" || exit
@@ -72,9 +76,10 @@ echo "❄️ Rebuilding NixOS..."
 shopt -s globstar
 eval set -- "$(getopt -o d --long dry-run: -- "$@")"
 
+dry_run=false
 while true; do
     case "$1" in
-        -d|--dry-run) dry_run=true shift;;
+        -d|--dry-run) dry_run=true; shift;;
         --) shift; break;;
         *) echo "Usage: $0 [-d|--dry-run]"; exit 1;;
     esac
@@ -83,4 +88,4 @@ done
 git diff -U0 -- **/*.nix
 
 choose_host
-rebuild dry_run
+rebuild "$dry_run"
